baseURL = ""
theme = "introduction"
DefaultContentLanguage = "en"
themesDir = "themes"
publishDir = "public"

[params]
themeStyle = "auto"
favicon = "/img/fav.ico"
showRSSButton = false
fadeIn = true
fadeInIndex = false
dateFormat = "Jan 2, 2006"
email = "youremail@email.com"

  [params.home]
  introHeight = "fullheight"
  showLatest = true
  showAllPosts = false
  allPostsArchiveFormat = true
  numberOfProjectsToShow = 3
  localTime = true
  timeZone = "America/Los_Angeles"
  timeFormat = "en-US"

  [params.projects]
  useTwoColumns = false

  [params.share]
  twitter = true
  facebook = true
  pinterest = true

  [[params.social]]
  url = "https://twitter.com/"
  icon = "twitter"
  icon_pack = "fab"

  [[params.social]]
  url = "https://facebook.com/"
  icon = "facebook-f"
  icon_pack = "fab"

  [[params.social]]
  url = "https://linkedin.com/"
  icon = "linkedin-in"
  icon_pack = "fab"

  [[params.social]]
  url = "mailto:youremail@email.com"
  icon = "paper-plane"
  icon_pack = "fas"

  [[params.social]]
  url = "https://mastodon.social/"
  icon = "mastodon"
  icon_pack = "fab"
  html_attributes = 'rel="me"'

[taxonomies]
tag = "tags"
series = "series"

[markup]
defaultMarkdownHandler = "goldmark"

[markup.goldmark.renderer]
unsafe = true

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "friendly"
  tabWidth = 4

[languages.en]
languageName = "English"
languageCode = "en-us"
contentDir = "content/en"
weight = 0
title = "Introduction"

  [languages.en.params]
  description = "Website Description"

[languages.es]
languageName = "Español"
languageCode = "es"
contentDir = "content/es"
weight = 1
title = "Introducción"

  [languages.es.params]
  description = "Descripcion del sitio web"

[languages.de]
languageName = "Deutsch"
languageCode = "de"
contentDir = "content/de"
weight = 2
title = "Vorstellung"

  [languages.de.params]
  dateFormat = "2. January 2006"
  description = "Beschreibung der Webseite"
